### ISSUE TITLE
Uncaught exception:  Error: .matrix_heartbeat.Beat#services is not a field: undefined

### ISSUE THREAD

**Issue by adrian2lee** [matrix-io/matrix-os#40]
```
==== Application faceTest started! ====
Uncaught exception:  Error: .matrix_heartbeat.Beat#services is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2472:35)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at Object.beat (/home/pi/matrix-os/lib/device/heartbeat.js:92:16)
    at Timeout._repeat (/home/pi/matrix-os/lib/device/heartbeat.js:24:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5) Error: .matrix_heartbeat.Beat#services is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2472:35)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at Object.beat (/home/pi/matrix-os/lib/device/heartbeat.js:92:16)
    at Timeout._repeat (/home/pi/matrix-os/lib/device/heartbeat.js:24:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
UNKNOWN ERROR! Error: .matrix_heartbeat.Beat#services is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2472:35)
    at MessagePrototype.set (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/home/pi/matrix-os/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at Object.beat (/home/pi/matrix-os/lib/device/heartbeat.js:92:16)
    at Timeout._repeat (/home/pi/matrix-os/lib/device/heartbeat.js:24:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Unable to clean, exitting...

```

i tried removing node_modules and reinstalling with npm install, didnt work. Any ideas?
This happens with faceTest, demographicTest and gestureTest

**Comment by adrian2lee** [comment]
Solved doing this again( I think):
`git submodule update --init`

**Comment by brianofrokk3r** [comment]
@adrian2lee this is confirmed as the resolution, thanks!
```
git submodule update --init
```
