### ISSUE TITLE
MATRIX OS - Receiving App Events via Input (or in general) - e.g. Input from Dashboard to MATRIX OS App.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#73]
Receiving App Events via Input (or in general) - e.g. Input from Dashboard to MATRIX OS App.

```
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:122:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
  app [M]>(CT)>app( recogTest2 { type: 'app-message', eventName: 'searchName', value: 'David' } +2ms
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:122:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
  app [M]>(CT)>app( recogTest2 { type: 'app-message', eventName: 'searchName', value: 'David' } +1ms
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:122:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
  app [M]>(CT)>app( recogTest2 { type: 'app-message', eventName: 'searchName', value: 'David' } +2ms
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:122:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
```

**Comment by eighteyes** [comment]
The app is closing before this.

**Comment by brianofrokk3r** [comment]
```
==== Application recogTest2 started! ====
  stream [M]->SS app-config { configVersion: 2,
  dataTypes: { name: { count: 'int', name: 'string' } },
  description: 'recognition demo',
  displayName: 'Recognition Test',
  events: [ 'train', 'recog', 'reset', 'searchName' ],
  keywords: 'cv',
  name: 'recogTest2',
  screens: [ [ 'name' ], [ 'controls' ], [ 'uniques' ] ],
  services: { re: { engine: 'recognition', type: 'face' } },
  widgets:
   { controls:
      { control: 'button',
        label: 'Recognition Controls',
        map: [Object],
        name: 'controls',
        type: 'controls',
        keys: [Object] },
     name:
      { control: 'input',
        event: 'searchName',
        label: 'Tag or Search',
        value: 'David',
        name: 'name',
        type: 'name',
        keys: [Object] },
     uniques:
      { display: 'list-group',
        format: 'sum',
        groupby: 'name',
        keys: [Object],
        label: 'Uniques',
        type: 'name',
        name: 'uniques' } },
  validated: true } +7ms
  engine.io-client:socket flushing 1 packets in socket +57ms
  engine.io-client:socket socket receive: type "pong", data "undefined" +45ms
(recogTest2) Matrix OS Application Library Loading...

  stream [M]->SS app-log 2017-03-28T20:59:04 l o g [recogTest2] Matrix OS Application Library Loading...
 +2s
  engine.io-client:socket flushing 1 packets in socket +2s
  app-event [M]->#0 { r: 128, g: 0, b: 0, a: 1 } +45ms
(recogTest2) [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message

  stream [M]->SS app-log 2017-03-28T20:59:04 l o g [recogTest2] [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
 +96ms
  engine.io-client:socket flushing 1 packets in socket +141ms
(recogTest2) [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
[M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message

  stream [M]->SS app-log 2017-03-28T20:59:04 l o g [recogTest2] [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
[M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
 +2ms
  engine.io-client:socket flushing 1 packets in socket +3ms
(recogTest2) [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
[M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message

  stream [M]->SS app-log 2017-03-28T20:59:04 l o g [recogTest2] [M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
[M]->app { eventType: 'container-ready', app: 'recogTest2', pid: 5638 } app-recogTest2-message
 +7ms
  engine.io-client:socket flushing 1 packets in socket +7ms
  heartbeat activeApp-> recogTest2  { re: { engine: 'recognition', type: 'face' } } +3s
[]
[ 'FACE_RECOGNITION' ]
  device.network Error getting wireless devices information wpa_cli -i wlan0 status +4s
  engine.io-client:socket socket receive: type "message", data "{"channel":"cli-message","payload":{"type":"trigger","payload":{"type":"trigger","eventName":"searchName","value":"Brian"},"deviceId":"dded01e09bf1","userId":"54529b61d28fb10200dc4904","eventName":"searchName"}}" +7s
  stream SS> cli-message : { type: 'trigger',
  payload: { type: 'trigger', eventName: 'searchName', value: 'Brian' },
  deviceId: 'dded01e09bf1',
  userId: '54529b61d28fb10200dc4904',
  eventName: 'searchName' } +579ms
  app =(CLI)>>>> trigger { type: 'trigger', eventName: 'searchName', value: 'Brian' } +2ms
  app-event trigger msg>  { type: 'trigger', eventName: 'searchName', value: 'Brian' } +0ms
  app [M]>(CT)>app( recogTest2 { type: 'trigger', eventName: 'searchName', value: 'Brian' } +1ms
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:122:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
  app [M]>(CT)>app( recogTest2 { type: 'app-message', eventName: 'searchName', value: 'Brian' } +4ms
(recogTest2) [M]->app { type: 'app-message', eventName: 'searchName', value: 'Brian' } app-recogTest2-message

  stream [M]->SS app-log 2017-03-28T20:59:12 l o g [recogTest2] [M]->app { type: 'app-message', eventName: 'searchName', value: 'Brian' } app-recogTest2-message
 +4ms
  engine.io-client:socket flushing 1 packets in socket +11ms
(recogTest2) [M]->app(msg) { type: 'app-message', eventName: 'searchName', value: 'Brian' }
[M]->app { type: 'app-message', eventName: 'searchName', value: 'Brian' } app-recogTest2-message

  stream [M]->SS app-log 2017-03-28T20:59:12 l o g [recogTest2] [M]->app(msg) { type: 'app-message', eventName: 'searchName', value: 'Brian' }
[M]->app { type: 'app-message', eventName: 'searchName', value: 'Brian' } app-recogTest2-message
 +2ms
```

**Comment by gordinh** [comment]
@brianofrokk3r can you give me more details of this app? I tested here the input event with some apps and worked fine for me.

**Comment by brianofrokk3r** [comment]
Any app will throw this error. If it's not reproducible we can close.

**Comment by gordinh** [comment]
OK, i could reproduce here with the ClickGames app too.
`==== Application ClickGames started! ==== 
(ClickGames) Matrix OS Application Library Loading...

(ClickGames) [M]->app { eventType: 'container-ready', app: 'ClickGames', pid: 4764 } app-ClickGames-message

(ClickGames) [M]->app { eventType: 'container-ready', app: 'ClickGames', pid: 4764 } app-ClickGames-message

[]
(ClickGames) [M]() send -> { lives: 3,
  failedHitsCounter: 0,
  okHitsCounter: 0,
  perfectHitsCounter: 0,
  score: 0,
  status: 'Main menu' }

[]
(ClickGames) Key:  failedHitsCounter 
Type:  int 
message[key]:  0 number

(ClickGames) Key:  lives 
Type:  int 
message[key]:  3 number
Key:  okHitsCounter 
Type:  int 
message[key]:  0 number
Key:  perfectHitsCounter 
Type:  int 
message[key]:  0 number
Key:  score 
Type:  int 
message[key]:  0 number
Key:  status 
Type:  string 
message[key]:  Main menu string

[]
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
(ClickGames) [M]->app { type: 'app-message', eventName: 'leftClick' } app-ClickGames-message

(ClickGames) [M]->app(msg) { type: 'app-message', eventName: 'leftClick' }

(ClickGames) [M]() send -> { lives: 3,
  failedHitsCounter: 0,
  okHitsCounter: 0,
  perfectHitsCounter: 0,
  score: 0,
  status: 'Quick Play' }

(ClickGames) Key:  failedHitsCounter 
Type:  int 
message[key]:  0 number
Key:  lives 
Type:  int 
message[key]:  3 number
Key:  okHitsCounter 
Type:  int 
message[key]:  0 number
Key:  perfectHitsCounter 
Type:  int 
message[key]:  0 number
Key:  score 
Type:  int 
message[key]:  0 number
Key:  status 
Type:  string 
message[key]:  Quick Play string

(ClickGames) [M]->app { type: 'app-message', eventName: 'leftClick' } app-ClickGames-message
[M]->app(msg) { type: 'app-message', eventName: 'leftClick' }

`

**Comment by gordinh** [comment]
Ok i could reproduce too with the ClickGames.
```
==== Application ClickGames started! ==== 
(ClickGames) Matrix OS Application Library Loading...

(ClickGames) [M]->app { eventType: 'container-ready', app: 'ClickGames', pid: 4764 } app-ClickGames-message

(ClickGames) [M]->app { eventType: 'container-ready', app: 'ClickGames', pid: 4764 } app-ClickGames-message

[]
(ClickGames) [M]() send -> { lives: 3,
  failedHitsCounter: 0,
  okHitsCounter: 0,
  perfectHitsCounter: 0,
  score: 0,
  status: 'Main menu' }

[]
(ClickGames) Key:  failedHitsCounter 
Type:  int 
message[key]:  0 number

(ClickGames) Key:  lives 
Type:  int 
message[key]:  3 number
Key:  okHitsCounter 
Type:  int 
message[key]:  0 number
Key:  perfectHitsCounter 
Type:  int 
message[key]:  0 number
Key:  score 
Type:  int 
message[key]:  0 number
Key:  status 
Type:  string 
message[key]:  Main menu string

[]
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
Error Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at EventEmitter.<anonymous> (/home/pi/matrix-os/lib/service/manager.js:343:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.triggerHandler (/home/pi/matrix-os/lib/event/app.js:237:21)
    at EventEmitter.cliMessageHandler (/home/pi/matrix-os/lib/event/server.js:124:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Socket.<anonymous> (/home/pi/matrix-os/lib/service/stream.js:164:21)
    at Socket.Emitter.emit (/home/pi/matrix-os/node_modules/component-emitter/index.js:133:20)
(ClickGames) [M]->app { type: 'app-message', eventName: 'leftClick' } app-ClickGames-message

(ClickGames) [M]->app(msg) { type: 'app-message', eventName: 'leftClick' }

(ClickGames) [M]() send -> { lives: 3,
  failedHitsCounter: 0,
  okHitsCounter: 0,
  perfectHitsCounter: 0,
  score: 0,
  status: 'Quick Play' }

(ClickGames) Key:  failedHitsCounter 
Type:  int 
message[key]:  0 number
Key:  lives 
Type:  int 
message[key]:  3 number
Key:  okHitsCounter 
Type:  int 
message[key]:  0 number
Key:  perfectHitsCounter 
Type:  int 
message[key]:  0 number
Key:  score 
Type:  int 
message[key]:  0 number
Key:  status 
Type:  string 
message[key]:  Quick Play string

(ClickGames) [M]->app { type: 'app-message', eventName: 'leftClick' } app-ClickGames-message
[M]->app(msg) { type: 'app-message', eventName: 'leftClick' }
```
